File/urls.py
from django.conf.urls import url
from File.views import filelist_with_form,delete_file,detail_file,big_file_download
urlpatterns = [

    url(r'^$', filelist_with_form),
    url(r'^(?P<pk>[0-9]+)/delete/$', delete_file),
    url(r'^(?P<pk>[0-9]+)/detail/$', detail_file),
    url(r'^(?P<pk>[0-9]+)/download/$',big_file_download),
]

FileWebApp/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^file/',include('File.urls')),
    url(r'^', include('File.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

File/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib import admin
from datetime import datetime
from django.utils import timezone

import uuid,os
# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


# Create your models here.

class TimeStampModel(models.Model):
    #created_date = models.DateTimeField(default=timezone.now(), blank=True)
    created_date = models.DateTimeField(auto_now_add=True,blank=True)
    class Meta:
        abstract = True

# generating unique id for each file
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('files', filename)

#file model
class File(TimeStampModel):
    filename_text = models.CharField(max_length=20)
    description_text = models.CharField(max_length=200)
    file = models.FileField(upload_to=get_file_path)

    def __str__(self):
        return self.filename_text

# receive the pre_delete signal and call the delete method on the FileField object
@receiver(pre_delete, sender=File)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.file.delete(False)


class FileAdmin(admin.ModelAdmin):
    list_display = ('filename_text','created_date')

admin.site.register(File,FileAdmin)

File/forms.py
from django import forms
from models import File
from django.forms import ModelForm


class UploadFileForm(ModelForm):

    class Meta:
        model = File
        fields = ('filename_text', 'description_text','file')

File/views.py
from File.models import File
from File.forms import UploadFileForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.conf import settings
from django.http import StreamingHttpResponse,HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
# view for file list page
def filelist_with_form(request):
    file_list = File.objects.all()
    # Show 7 files per page
    paginator = Paginator(file_list, 7)
    # get page ID from URL
    page = request.GET.get('page')

    # pagination
    try:
        files = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        files = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        files = paginator.page(paginator.num_pages)

    # if a POST request , save the file
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UploadFileForm(request.POST, request.FILES)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = UploadFileForm()

    return render(request,'file_list_page.html',{'files':files,'form': form})

#view for deleting files
def delete_file(request,pk):
    File.objects.filter(id=pk).delete()
    return HttpResponseRedirect('/')

#view for file detail page
def detail_file(request,pk):
    file = File.objects.get(id=pk)
    return render(request,'file_detail_page.html',{'file':file})

# view for downloading files
def big_file_download(request,pk):
    # get file by id
    file = File.objects.get(id=pk)

    def file_iterator(file_name, chunk_size=512):
        with open(file_name,"rb") as f:
            while True:
                c = f.read(chunk_size)
                if c:
                    yield c
                else:
                    break

    the_file_name = settings.MEDIA_ROOT+"/"+str(file.file)

    response = StreamingHttpResponse(file_iterator(the_file_name))
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(str(file.file))

    return response

File/templates/file_detail_page.html
{% extends 'base.html' %}

{% block content_tilte %}

    Detail
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 50px">

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><b>File Name :</b>{{ file.filename_text }}</div>
                    <!-- Table -->
                    <table class="table">
                        <tr>
                            <td><b>File Description :</b>{{ file.description_text }}</td>
                        </tr>

                        <tr>
                            <td><b>File Created Date :</b>{{ file.created_date }}</td>
                        </tr>
                        <tr>
                            <td style="">

                                <a  href="/{{ file.id}}/download/" class="btn btn-primary btn-block center-block" style="width: 30%">Download File</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

File/templates/file_list_page.html
{% extends 'base.html' %}
{% block content_tilte %}

    Home
{% endblock %}


{% block content %}
    <div class="container" style="margin-top: 50px">

        <div class="row">
            <div class="col-md-7">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">Files</div>

                    <!-- Table -->
                    <table class="table">
                        <tr>
                            <th>File name</th>
                            <th>View</th>
                            <th>Remove</th>
                        </tr>
                        {% for file in files %}
                            <tr>
                                <td>{{ file.filename_text }}</td>
                                <td width="20%">
                                    <a href="{{ file.id }}/detail/" class="glyphicon glyphicon-zoom-in"
                                       aria-hidden="true"/>
                                </td>
                                <td width="20%">
                                    <a href="{{ file.id }}/delete/" class="glyphicon glyphicon glyphicon-trash"
                                       aria-hidden="true"/>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                <div style="text-align: center">
                    <div class="pagination">
                        <span class="step-links">
                            {% if files.has_previous %}
                                <a href="?page={{ files.previous_page_number }}">
                                    <b> <<&nbsp;&nbsp; </b>
                                </a>
                            {% endif %}

                            <span class="current">
                                    page <b style="color: blue">{{ files.number }}</b> of {{ files.paginator.num_pages }}
                            </span>

                            {% if files.has_next %}
                                <a href="?page={{ files.next_page_number }}">
                                <b> &nbsp;&nbsp;>> </b>
                                </a>
                            {% endif %}
                        </span>

                    </div>
                </div>
            </div>

            <div class="col-md-3" style="margin-left: 50px">

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_filename_text">File name</label>
                        <input type="text" class="form-control" id="id_filename_text" name="filename_text">
                    </div>
                    <div class="form-group">
                        <label for="id_description_text">File desc</label>
                        <textarea class="form-control" rows="3" id="id_description_text" name="description_text">
                        </textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_file">File input</label>
                        <input type="file" id="id_file" name="file">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>


            </div>
        </div>

    </div>
{% endblock %}

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block content_tilte %}
        {% endblock %}
    </title>
     <!-- Bootstrap core CSS -->
    <link href={% static "bootstrap-3.3.7-dist/css/bootstrap.min.css"%} rel="stylesheet">

    <link href={% static "starter-template.css"%} rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">File App</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>